version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    tty: true
    stdin_open: true
    working_dir: /app
    command: zsh
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_USER: root
      DB_ROOT_PASSWORD: pass
      DB_PORT: 3306
      DB_NAME: chat
      NODE_SERVER_PORT: 3001
    depends_on:
      - db
    networks:
      - chat_net
    restart: always

  db:
    image: mysql:8.0.23
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    restart: always
    networks:
      - chat_net

networks:
  chat_net:
    driver: bridge