version: '3'

services:
  db:
    build: db/
    container_name: db
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
  backend:
    build: backend/
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - db